### ISSUE TITLE
Allow tuning max requests per keepalive connection

### ISSUE THREAD

**Issue by djones6** [IBM-Swift/Kitura#1125]
I've been investigating Kitura's poor performance on OSX with https://github.com/tbrand/which_is_the_fastest

It appears that the benchmark client (written in crystal) doesn't perform well when having to establish new connections to the server.  Out of the 3 swift frameworks, looks like we're the only one that implements a limited number of requests per connection. Closing the connection every 100 requests really hurts the performance with this client.

Ideally I'd like to be able to increase the value (or disable the feature altogether). However, [the tunable in IncomingHTTPSocketProcessor.swift](https://github.com/IBM-Swift/Kitura-net/blob/1.7.12/Sources/KituraNet/HTTP/IncomingHTTPSocketProcessor.swift#L53) is private.

With the default (100), the benchmark reports:
```
bananas:which_is_the_fastest djones6$ ./bin/benchmarker swift
Language (Runtime)        Framework (Middleware)          Max [sec]       Min [sec]       Ave [sec]
------------------------- ------------------------- --------------- --------------- ---------------
swift                     vapor                            5.966822        5.813013        5.876588
swift                     perfect                          7.279527        7.109674        7.193408
swift                     kitura                          19.610924       18.156477       18.905314
```
But if I increase it to 100,000:
```
swift                     kitura                           6.989094        6.808682        6.898933
```
Currently, the only way I could 'fix' this would be some ugly hack in the makefile to edit the Kitura-net dependency before building.

**Comment by shmuelk** [comment]
@djones6 Can you please post here the headers from the request and the response from one of the requests in the benchmark? It would help, if it was done for each of the frameworks.

**Comment by djones6** [comment]
The client repeats a sequence of two GETs and a POST.  Here's the sequence for a single loop:

### Kitura:
```
Request:
    GET / HTTP/1.1\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Date: Mon, 03 Jul 2017 13:52:58 GMT\r\n
    Content-Length: 0\r\n
    Connection: Keep-Alive\r\n
    Keep-Alive: timeout=60, max=99\r\n
Request:
    GET /user/0 HTTP/1.1\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Date: Mon, 03 Jul 2017 13:52:58 GMT\r\n
    Content-Length: 1\r\n
    Connection: Keep-Alive\r\n
    Keep-Alive: timeout=60, max=98\r\n
Request:
    POST /user HTTP/1.1\r\n
    Content-Length: 0\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Date: Mon, 03 Jul 2017 13:52:58 GMT\r\n
    Content-Length: 0\r\n
    Connection: Keep-Alive\r\n
    Keep-Alive: timeout=60, max=97\r\n
```
### Vapor:
```
Request:
    GET / HTTP/1.1\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Content-Type: text/plain; charset=utf-8\r\n
    Content-Length: 0\r\n
Request:
    GET /user/0 HTTP/1.1\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Content-Type: text/plain; charset=utf-8\r\n
    Content-Length: 1\r\n
Request:
    POST /user HTTP/1.1\r\n
    Content-Length: 0\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Content-Type: text/plain; charset=utf-8\r\n
    Content-Length: 0\r\n
```
### Perfect:
```
Request:
    GET / HTTP/1.1\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Connection: Keep-Alive\r\n
    Content-Length: 0\r\n
Request:
    GET /user/0 HTTP/1.1\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Connection: Keep-Alive\r\n
    Content-Length: 1\r\n
Request:
    POST /user HTTP/1.1\r\n
    Content-Length: 0\r\n
    Host: localhost:3000\r\n
    User-Agent: Crystal\r\n
    Accept-Encoding: gzip, deflate\r\n
Response:
    HTTP/1.1 200 OK\r\n
    Connection: Keep-Alive\r\n
    Content-Length: 0\r\n
```
